after_success:
  - bundle exec codeclimate-test-reporterlanguage: ruby
sudo: false
cache: bundler
addons:
  postgresql: '9.4'
services:
  - postgresql
before_install:
- export TZ=Europe/London
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
# Please don't add extra test commands here unless they are Travis only -- Jenkins will run this script too
script: bash ./runtests.sh
