version: '2'
services:
  db:
    image: postgres:9.5.3
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    env_file:
      - .docker-secrets.env
    ports:
      - "3000:3000"
    links:
      - db:database
    volumes:
      - .:/rails